import { Router } from "express";
import adminAuthRoutes from "./adminAuthRoutes.js";
import publicCarRoutes from "./publicCarRoutes.js";
import adminCarRoutes from "./adminCarRoutes.js";
import publicBookingRoutes from "./publicBookingRoutes.js";
import adminBookingRoutes from "./adminBookingRoutes.js";
import publicContactRoutes from "./publicContactRoutes.js";
import adminMessageRoutes from "./adminMessageRoutes.js";
import dashboardRoutes from "./dashboardRoutes.js";
import settingsRoutes from "./settingsRoutes.js";
import publicSettingsRoutes from "./publicSettingsRoutes.js";
const router = Router();
router.get("/health", (_req, res) => { res.status(200).json({ message: "API is running" }); });
router.use("/admin", adminAuthRoutes);
router.use("/cars", publicCarRoutes);
router.use("/bookings", publicBookingRoutes);
router.use("/contact", publicContactRoutes);
router.use("/settings", publicSettingsRoutes);
router.use("/admin/cars", adminCarRoutes);
router.use("/admin/bookings", adminBookingRoutes);
router.use("/admin/messages", adminMessageRoutes);
router.use("/admin/dashboard", dashboardRoutes);
router.use("/admin/settings", settingsRoutes);
export default router;
